name: Build, Push, and Test Grafana Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-push-test:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build . -t karthikreddy805/grafana:latest

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Push Docker image
        run: docker push karthikreddy805/grafana:latest
        
      - name: Run Prometheus on host port 9091
        run: |
          docker run -d \
            --name prometheus \
            -p 9091:9090 \
            -v ${{ github.workspace }}/prometheus.yml:/etc/prometheus/prometheus.yml \
            prom/prometheus:latest
            
      - name: Run Grafana container (for testing only)
        run: |
          docker run -d -p 3001:3000 --name grafana-${GITHUB_RUN_ID} karthikreddy805/grafana:latest          
          sleep 10
          docker ps
          docker logs test-grafana
